import os

from dotenv import load_dotenv

load_dotenv()
# ============================================================
# INVESTIGATION AGENT CONFIGURATION
# ============================================================


# ------------------------------------------------------------
# 1. LLM CONFIGURATION
# ------------------------------------------------------------

# Current POC provider.
# Later this can be changed without rewriting the agent.
LLM_PROVIDER = os.getenv(
    "LLM_PROVIDER",
    "groq"
)

LLM_MODEL = os.getenv(
    "LLM_MODEL",
    "openai/gpt-oss-120b"
)

LLM_API_KEY = os.getenv(
    "LLM_API_KEY",
    ""
)


# ------------------------------------------------------------
# 2. LLM GENERATION SETTINGS
# ------------------------------------------------------------

# Keep temperature low because this is an
# evidence-based reverse-engineering system.
LLM_TEMPERATURE = 0.1

# Maximum output tokens generated by the investigation model.
LLM_MAX_TOKENS = 4096


# ------------------------------------------------------------
# 3. NEO4J CONFIGURATION
# ------------------------------------------------------------

NEO4J_ENABLED = os.getenv(
    "NEO4J_ENABLED",
    "false"
).lower() == "true"

NEO4J_URI = os.getenv(
    "NEO4J_URI",
    "bolt://localhost:7687"
)

NEO4J_USERNAME = os.getenv(
    "NEO4J_USERNAME",
    "neo4j"
)

NEO4J_PASSWORD = os.getenv(
    "NEO4J_PASSWORD",
    ""
)


# ------------------------------------------------------------
# 4. QDRANT CONFIGURATION
# ------------------------------------------------------------

QDRANT_ENABLED = os.getenv(
    "QDRANT_ENABLED",
    "false"
).lower() == "true"

QDRANT_URL = os.getenv(
    "QDRANT_URL",
    "http://localhost:6333"
)

QDRANT_API_KEY = os.getenv(
    "QDRANT_API_KEY",
    ""
)

QDRANT_COLLECTION = os.getenv(
    "QDRANT_COLLECTION",
    "legacy_knowledge"
)


# ------------------------------------------------------------
# 5. RETRIEVAL SETTINGS
# ------------------------------------------------------------

# Number of vector-search results to retrieve.
QDRANT_TOP_K = 5

# Minimum similarity score.
QDRANT_SCORE_THRESHOLD = 0.30

# Maximum graph results returned to the agent.
NEO4J_RESULT_LIMIT = 20


# ------------------------------------------------------------
# 6. AGENT BEHAVIOUR
# ------------------------------------------------------------

# The Investigation Agent should not answer unsupported
# project-specific questions from the LLM's general knowledge.
EVIDENCE_REQUIRED = True

# Minimum evidence items expected before claiming high confidence.
MIN_EVIDENCE_FOR_HIGH_CONFIDENCE = 2


# ------------------------------------------------------------
# 7. MOCK MODE
# ------------------------------------------------------------

# For development while Neo4j and Qdrant are not ready.
USE_MOCK_RETRIEVERS = os.getenv(
    "USE_MOCK_RETRIEVERS",
    "true"
).lower() == "true"